"""v3 schema

Revision ID: 8f9dd5acf2d8
Revises: 
Create Date: 2026-03-07 12:55:51.836778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9dd5acf2d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dsa_problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.String(length=100), nullable=True))

    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('resume_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('suggestions_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('missing_skills_json', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('job_readiness_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_solved_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('tech_score_sum', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hr_score_sum', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('aptitude_score_sum', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tech_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hr_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('aptitude_attempts', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('aptitude_attempts')
        batch_op.drop_column('hr_attempts')
        batch_op.drop_column('tech_attempts')
        batch_op.drop_column('aptitude_score_sum')
        batch_op.drop_column('hr_score_sum')
        batch_op.drop_column('tech_score_sum')
        batch_op.drop_column('last_solved_date')
        batch_op.drop_column('max_streak')
        batch_op.drop_column('current_streak')
        batch_op.drop_column('job_readiness_score')
        batch_op.drop_column('username')

    with op.batch_alter_table('resume_data', schema=None) as batch_op:
        batch_op.drop_column('missing_skills_json')
        batch_op.drop_column('suggestions_json')
        batch_op.drop_column('score')

    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('dsa_problems', schema=None) as batch_op:
        batch_op.drop_column('topic')

    # ### end Alembic commands ###
